# Site settings
title: Ascentcore Website
tagline: "Best quality. No trade-offs."
url: "http://ascentcore.com" # The base hostname & protocol for your site. Use it if you need absolute URL's
version: 0.0.1

# Social
#socialimg: /img/social.jpg # be sure to change this image
#facebook: fbusername
#twitter: twusername
github: ascentcore
#instagram: igusername

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'

# Contact
#phone: "916-276-1044" # This is my real number. You should text me.
email: "contact@ascentcore.com" # This is my real email address. Please don't email me.

# Use this for production
sass:
  sass_dir:         _sass
  style:            :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

authors:
  sarapopa:
    name: Sara Popa
    email: sara.popa@ascentcore.com
    description: Machine Learning Engineer as part of the Ascentcore Research Lab team
  corinaadam:
    name: Corina Adam
    email: corina.adam@ascentcore.com
    description: Fullstack engineer as part of the Ascentcore Fontend Development team